### ISSUE TITLE
Avatar view no longer works.

### ISSUE THREAD

**Issue by traviswimer** [traviswimer/PlugPro#5]
It clearly doesn't...

**Comment by andrewtibbetts** [comment]
Anything specific? I don't see anything out of place / not functioning.

**Comment by traviswimer** [comment]
Yea, I was thinking the same thing. I must have done something weird to break it. I'll create an issue that actual explains things if I ever see it messed up again.

**Comment by andrewtibbetts** [comment]
Maybe you saw this happening on Pro view? Button positions fix themselves on window resize or selecting Pro view from another view. Chat and both DJ lists only show once you select Pro view from another view.

![image](https://cloud.githubusercontent.com/assets/296908/7129697/4f473c22-e229-11e4-8311-62b16d56c7f5.png)

**Comment by traviswimer** [comment]
Well, that definitely is a problem either way.
