### ISSUE TITLE
Some Pro view elements don't show or are mispositioned on load

### ISSUE THREAD

**Issue by andrewtibbetts** [traviswimer/PlugPro#9]
In Pro view, Join/Leave Waitlist & Woot/Meh/Grab boxes start in Avatar view position (positions properly on resize or view change). Also, the DJ Waitlist and All DJs lists don't show on load (shows on view change).

![screen shot 2015-04-13 at 9 48 33 pm](https://cloud.githubusercontent.com/assets/296908/7242801/9a40652a-e78b-11e4-8462-c015b3d0ca32.png)

**Comment by andrewtibbetts** [comment]
The lists pop in when the song changes, too.

**Comment by traviswimer** [comment]
Actually I lied...
